server:
  port: ${PORT:8888}
  
spring:
  application:
    name: dummy-config-server
  cloud:
    config:
      server:
        git:
          url: https://github.com/AmanKishan/dummy-config-server.git
          searchPaths: 

logging:
  level:
    com.dummy.configserver: DEBUG          